<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>netstandard2.1;net10.0</TargetFrameworks>
    <Nullable>enable</Nullable>
    <LangVersion>14</LangVersion>
    <PackageId>AndanteSoft.CoreMathSharp</PackageId>
    <PackageVersion>1.0.0</PackageVersion>
    <Authors>Andante</Authors>
    <Description></Description>
    <Copyright>Copyright (c) Andante 2026</Copyright>
    <PackageProjectUrl>https://github.com/andanteyk/CoreMathSharp</PackageProjectUrl>
    <PackageIcon>CoreMathSharp.png</PackageIcon>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <RepositoryUrl>https://github.com/andanteyk/CoreMathSharp</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
    <PackageTags>C# Math</PackageTags>
    <PackageLicenseFile>LICENSE.md</PackageLicenseFile>
  </PropertyGroup>

  <ItemGroup>
    <None Include="$(SolutionDir)LICENSE.md" Pack="true" PackagePath="" />
    <None Include="$(SolutionDir)THIRD-PARTY.md" Pack="true" PackagePath="" />
    <None Include="$(SolutionDir)README.md" Pack="true" PackagePath="" />
    <None Include="$(SolutionDir)CoreMathSharp.png" Pack="true" PackagePath="" />
  </ItemGroup>

</Project>
